### ISSUE TITLE
Python string representations used for default and enum values

### ISSUE THREAD

**Issue by matt-graham** [RalfG/jsonschema2md#14]
Currently the values associated with the `default` and `enum` keywords on properties are displayed as their corresponding Python string representations in the Markdown translation. For example

`"default": null` &rightarrow; Default: `None`
`"default": true` &rightarrow; Default: `True`
`"default": "a string"` &rightarrow; Default: `a string`
`"enum": ["option 1", "option 2"]` &rightarrow; Must be one of: `['option 1', 'option 2']`

As these are meant to represent possible values in a JSON file it seem like it would be preferable to use the corresponding JSON string representations, that is for the above examples we would have

`"default": null` &rightarrow; Default: `null`
`"default": true` &rightarrow; Default: `true`
`"default": "a string"` &rightarrow; Default: `"a string"`
`"enum": ["option 1", "option 2"]` &rightarrow; Must be one of: `["option 1", "option 2"]`

**Comment by RalfG** [comment]
This repo will be archived in favor of its fork at [sbrunner/jsonschema2md2](https://github.com/sbrunner/jsonschema2md2). If needed, a new issue can be opened there.
