### ISSUE TITLE
Ref is not supported

### ISSUE THREAD

**Issue by sbrunner** [RalfG/jsonschema2md#17]
E.g. here https://github.com/sbrunner/scan-to-paperless/blob/test/config.md
I get `Refer to #/definitions/auto_mask` but it can be a link.

For that, each definition should have a title...

Are you open that I do a pull request?

**Comment by sbrunner** [comment]
Fixed here https://pypi.org/project/jsonschema2md2/
With https://github.com/sbrunner/jsonschema2md2/pull/2

**Comment by RalfG** [comment]
Hi @sbrunner,

Apologies for being unresponsive up until now. You seem to have made quite some progress on your fork of the project. Would you like to merge back the changes into this repository? If so, I can definitely give you maintainer access to both the repo and the PyPI project. Let me know what you think.

Best,
Ralf

**Comment by sbrunner** [comment]
Yes, it can be good :-)
I will create a pull request for that :-)
