### ISSUE TITLE
Support for oneOf

### ISSUE THREAD

**Issue by durey** [RalfG/jsonschema2md#2]
Hi, I've checked that there is no support for `oneOf` clauses. Is it in the roadmap?

**Comment by RalfG** [comment]
Ideally the package would support the full JSON Schema specification, so yes! I initially only supported what I personally required. I'm currently short on time, but PRs are always welcome.

**Comment by RalfG** [comment]
This repo will be archived in favor of its fork at [sbrunner/jsonschema2md2](https://github.com/sbrunner/jsonschema2md2). If needed, a new issue can be opened there.
