### ISSUE TITLE
Make `tabsize` an argument

### ISSUE THREAD

**Issue by hyumo** [RalfG/jsonschema2md#22]
It seems that `tabsize` is set to `2` as a constant. However, popular python library `python-markdown` can only take tab length = 4. 

https://github.com/Python-Markdown/markdown/issues/451

**Comment by RalfG** [comment]
This repo will be archived in favor of its fork at [sbrunner/jsonschema2md2](https://github.com/sbrunner/jsonschema2md2). If needed, a new issue can be opened there.
